apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: dev  # The namespace to deploy your app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app-container
        image: "wil42/playground:v1"  # Replace with 'v2' for the v2 tag
        ports:
        - containerPort: 8080
